[package]
name = "phoony"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme-file = "README.md"
repository = "https://github.com/phoony/rust-lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
